# """
# main.py
# -------
# Syntra.AI – Task Management Microservice
# Entry point. Run with:  uvicorn main:app --reload
# Swagger UI at:          http://127.0.0.1:8000/docs
# """

# from fastapi import FastAPI, HTTPException, status
# from fastapi.middleware.cors import CORSMiddleware

# from models import (
#     ProjectDescriptionRequest,
#     DistributionRequest,
#     TaskGenerationResponse,
#     DistributionResponse,
#     HealthResponse,
# )
# from services import generate_tasks_from_llm, distribute_tasks
# from utils import MOCK_TEAM_MEMBERS

# # ── App Initialisation ────────────────────────────────────────────────────────

# app = FastAPI(
#     title="Syntra.AI — Task Management Microservice",
#     description=(
#         "Two core capabilities:\n\n"
#         "1. **AI Task Generation** — send a project description, receive a structured "
#         "JSON list of tasks (name, description, skills, difficulty).\n\n"
#         "2. **Smart Task Distribution** — send a task list, receive assignments "
#         "matched to team members by skill and workload."
#     ),
#     version="1.0.0",
#     contact={
#         "name": "Syntra.AI Team — Benha University",
#     },
#     license_info={"name": "MIT"},
# )

# # Allow all origins during development — tighten in production
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_methods=["*"],
#     allow_headers=["*"],
# )


# # ── Routes ────────────────────────────────────────────────────────────────────

# @app.get(
#     "/health",
#     response_model=HealthResponse,
#     tags=["Health"],
#     summary="Service health check",
# )
# async def health_check() -> HealthResponse:
#     """Returns a simple OK response to confirm the service is running."""
#     return HealthResponse()


# @app.post(
#     "/generate-tasks",
#     response_model=TaskGenerationResponse,
#     status_code=status.HTTP_200_OK,
#     tags=["AI Task Generation"],
#     summary="Generate a structured task list from a project description",
# )
# async def generate_tasks(body: ProjectDescriptionRequest) -> TaskGenerationResponse:
#     """
#     Send a natural-language project description and receive a validated list
#     of development tasks generated by Groq's LLM.

#     Each task includes:
#     - **Task_Name** — concise title
#     - **Description** — what needs to be done
#     - **Required_Skills** — skills needed
#     - **Difficulty_Level** — 1 (easy) to 10 (expert)
#     """
#     try:
#         tasks = await generate_tasks_from_llm(
#             project_description=body.project_description,
#             num_tasks=body.num_tasks,
#         )
#     except EnvironmentError as e:
#         raise HTTPException(status_code=500, detail=str(e))
#     except Exception as e:
#         raise HTTPException(
#             status_code=502,
#             detail=f"LLM call failed: {str(e)}",
#         )

#     return TaskGenerationResponse(
#         project_description=body.project_description,
#         total_tasks=len(tasks),
#         tasks=tasks,
#     )


# @app.post(
#     "/distribute-tasks",
#     response_model=DistributionResponse,
#     status_code=status.HTTP_200_OK,
#     tags=["Smart Task Distribution"],
#     summary="Assign tasks to team members based on skills and workload",
# )
# async def distribute(body: DistributionRequest) -> DistributionResponse:
#     """
#     Takes a list of tasks and distributes them across the mock team members
#     using a **greedy skill-match + workload-balance** algorithm:

#     1. Tasks are sorted hardest-first so critical work is placed first.
#     2. Each task is assigned to the member with the highest skill overlap.
#     3. Ties are broken by lowest current workload.
#     4. Tasks with zero skill match are returned in `unassigned_tasks`.
#     """
#     assigned, unassigned = distribute_tasks(body.tasks)

#     summary = {}
#     for at in assigned:
#         summary[at.assigned_to] = summary.get(at.assigned_to, 0) + 1

#     return DistributionResponse(
#         total_tasks=len(body.tasks),
#         assigned_tasks=assigned,
#         unassigned_tasks=unassigned,
#         distribution_summary=summary,
#     )


# @app.post(
#     "/generate-and-distribute",
#     response_model=DistributionResponse,
#     status_code=status.HTTP_200_OK,
#     tags=["AI Task Generation", "Smart Task Distribution"],
#     summary="One-shot: generate tasks AND distribute them in a single call",
# )
# async def generate_and_distribute(body: ProjectDescriptionRequest) -> DistributionResponse:
#     """
#     Convenience endpoint that chains both operations:
#     1. Calls Groq to generate tasks from the project description.
#     2. Immediately runs the distribution algorithm on the result.
#     """
#     try:
#         tasks = await generate_tasks_from_llm(
#             project_description=body.project_description,
#             num_tasks=body.num_tasks,
#         )
#     except EnvironmentError as e:
#         raise HTTPException(status_code=500, detail=str(e))
#     except Exception as e:
#         raise HTTPException(status_code=502, detail=f"LLM call failed: {str(e)}")

#     assigned, unassigned = distribute_tasks(tasks)
#     summary = {}
#     for at in assigned:
#         summary[at.assigned_to] = summary.get(at.assigned_to, 0) + 1

#     return DistributionResponse(
#         total_tasks=len(tasks),
#         assigned_tasks=assigned,
#         unassigned_tasks=unassigned,
#         distribution_summary=summary,
#     )


# @app.get(
#     "/team-members",
#     tags=["Smart Task Distribution"],
#     summary="List all mock team members and their skills",
# )
# async def list_team_members():
#     """Returns the mock team member database used for task distribution."""
#     return {"total": len(MOCK_TEAM_MEMBERS), "members": MOCK_TEAM_MEMBERS}
"""
main.py
-------
Syntra.AI – Task Management Microservice
Entry point. Run with:  uvicorn main:app --reload
Swagger UI at:          http://127.0.0.1:8000/docs
"""

from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query, status
from fastapi.middleware.cors import CORSMiddleware

from models import DistributionResponse, HealthResponse, TeamMember
from services import distribute_tasks, generate_tasks_from_llm

# ── App Initialisation ────────────────────────────────────────────────────────

app = FastAPI(
    title="Syntra.AI — Task Management Microservice",
    description=(
        "Two-step workflow:\n\n"
        "1. **POST `/set-team`** — upload your team members once.\n\n"
        "2. **GET `/generate-and-assign`** — describe your project; "
        "the API generates tasks via Groq and assigns them to your team automatically."
    ),
    version="2.0.0",
    contact={"name": "Syntra.AI Team — Benha University"},
    license_info={"name": "MIT"},
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── In-Memory Team Store ──────────────────────────────────────────────────────
# A simple server-level cache. Persists for the lifetime of the process.

_team_store: List[TeamMember] = []


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["Health"],
    summary="Service health check",
)
async def health_check() -> HealthResponse:
    """Returns a simple OK to confirm the service is running."""
    return HealthResponse()


@app.post(
    "/set-team",
    status_code=status.HTTP_200_OK,
    tags=["Team"],
    summary="Store team members for use in task assignment",
)
async def set_team(members: List[TeamMember]) -> dict:
    """
    Upload the list of team members that will be used by `/generate-and-assign`.

    Each member requires:
    - **id** — unique integer
    - **name** — full name
    - **skills** — list of skill strings
    - **current_workload** — tasks already assigned (default 0)

    Calling this endpoint again **replaces** the previously stored team.
    """
    if not members:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Team list must not be empty.",
        )

    global _team_store
    _team_store = members

    return {
        "message": f"Team of {len(_team_store)} member(s) stored successfully.",
        "members": [m.name for m in _team_store],
    }


@app.get(
    "/generate-and-assign",
    response_model=DistributionResponse,
    status_code=status.HTTP_200_OK,
    tags=["Tasks"],
    summary="Generate tasks from a project description and assign them to the stored team",
)
async def generate_and_assign(
    project_description: str = Query(
        ...,
        min_length=20,
        description="A detailed description of the project.",
        examples=["Build a student attendance and grading system with a web dashboard."],
    ),
    num_tasks: Optional[int] = Query(
        default=None,
        ge=1,
        le=20,
        description="How many tasks to generate (1–20). Omit to let the LLM decide.",
    ),
) -> DistributionResponse:
    """
    **Step 1** — Calls Groq (`llama-3.3-70b-versatile`) to break the project
    description into structured tasks.

    **Step 2** — Runs the skill-match + workload-balance algorithm to assign
    each task to the best available team member.

    > ⚠️ You must call **POST `/set-team`** at least once before using this endpoint.
    """
    if not _team_store:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Please set the team first using the /set-team endpoint.",
        )

    try:
        tasks = await generate_tasks_from_llm(
            project_description=project_description,
            num_tasks=num_tasks,
        )
    except EnvironmentError as exc:
        raise HTTPException(status_code=500, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"LLM call failed: {exc}")

    assigned, unassigned = distribute_tasks(tasks, team=_team_store)

    summary: dict = {}
    for at in assigned:
        summary[at.assigned_to] = summary.get(at.assigned_to, 0) + 1

    return DistributionResponse(
        total_tasks=len(tasks),
        assigned_tasks=assigned,
        unassigned_tasks=unassigned,
        distribution_summary=summary,
    )